version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_biblioteca
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: biblioteca_api
    ports:
      - "3333:3333"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://usuario:senha@postgres:5432/biblioteca?schema=public
      - JWT_SECRET=suaChaveSecretaJWT
      - PORT=3333
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             npm run dev"

volumes:
  postgres_data:
