FROM node:20-slim

# Instalações de dependências necessárias
RUN apt-get update && \
    apt-get install -y openssl bash && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package*.json tsconfig.json ./
COPY prisma ./prisma
COPY src ./src

RUN npm install

EXPOSE 3333

CMD ["npm", "run", "dev"]
